---
title: "dsvss_no_normalization_kraken2"
author: "Keri Burge"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r, eval=TRUE, echo=FALSE, message=FALSE}
#Read in the neccessary libraries
library(knitr)
library(ggplot2)
library(data.table)
library(viridis)
library(ggpubr) #has ggarange function
library(janitor)
library(rstatix)
library(ggrepel)
library(tidyverse)

```


```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```


# Colors
```{r, colors}
double_color <- "#04387a"
single_color <- "#6fbfdc"
  
```


# Metadata
```{r, metadata}
#Library info
metadata <- fread("./05-results/normalize_eager/dsvss_npre_w_rl_subsampling_metadata.tsv") %>%
  filter(!str_detect(Sequencing_ID, "bp")) %>%
  mutate(Sequencing_ID = str_replace(Sequencing_ID, "_10M", ""))

#Read counts throughout eager
read_counts <- fread("./05-results/normalize_eager/dsvss_npre_eager_read_counts.tsv")

#Combine tables
metadata <- metadata %>%
  full_join(., read_counts, by = c("Sequencing_ID", "Strandedness"))


```

#Counts throughout eager
```{r}
#Number of reads
eager <- metadata %>%
  pivot_longer(Adapter_removal_merged:Cutadapt_merged, names_to = "step", values_to = "reads") %>%
  mutate(step = (factor(step, levels = c("Adapter_removal_merged", "Remove_less_30bp_merged", "Artifact_removal_merged", "Cutadapt_merged")))) %>%
  mutate(step = str_replace_all(step, "Adapter_removal_merged", "Reads After Adapter Removal and Merging"),
         step = str_replace_all(step, "Remove_less_30bp_merged", "Reads After Removing Reads <30bp"),
         step = str_replace_all(step, "Artifact_removal_merged", "Reads After Removing Sequencing and Lab Artifacts"),
         step = str_replace_all(step, "Cutadapt_merged", "Reads After Cutadapt")) %>%
  rename(Library = Strandedness) %>%
  mutate(Library = str_replace_all(Library, "Single", "ssLib"),
         Library = str_replace_all(Library, "Double", "dsLib")) %>%
  mutate(reads = str_replace_all(reads, ",", "")) %>%
  mutate(reads = as.numeric(reads))
 
eager$step <- factor(eager$step, levels = c("Reads After Adapter Removal and Merging", "Reads After Removing Reads <30bp", "Reads After Removing Sequencing and Lab Artifacts", "Reads After Cutadapt")) 
  
percent_lost_30bp <- eager %>%
  select(Sequencing_ID, Library, step, reads) %>%
  pivot_wider(names_from = step, values_from = reads) %>%
  select(Sequencing_ID, Library, `Reads After Adapter Removal and Merging`, `Reads After Removing Reads <30bp`) %>%
  rename(adapter = `Reads After Adapter Removal and Merging`,
         remove_30 = `Reads After Removing Reads <30bp`) %>%
  mutate(percent_lost = ((adapter-remove_30)/adapter)*100) %>%
  group_by(Library) %>%
  summarise(
    average_percent_lost_30 = round(mean(percent_lost, na.rm = TRUE), 2),
    sd = round(sd(percent_lost, na.rm = TRUE), 2))

wilcox_results <- eager %>%
  group_by(step) %>%
  wilcox_test(reads ~ Library, paired = TRUE) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance("p.adj")


effect_size_labels <- eager %>%
  group_by(step) %>%
  wilcox_effsize(formula = reads ~ Library, paired = TRUE) %>%
  mutate(effectsize_cat = case_when(
    magnitude == "small" ~ "†",     
    magnitude == "moderate" ~ "††",
    magnitude == "large" ~ "†††"))


wilcox_results <- wilcox_results %>%
  left_join(effect_size_labels) %>%
  mutate(annotation = paste(p.adj.signif, effectsize_cat))

annotations <- wilcox_results %>%
  group_by(step) %>%
  summarize(annotation = first(annotation),
            y_position = 10.5, .groups = 'drop')

eager_counts_plots <- eager %>%
  mutate(reads = reads/1000000) %>%
  ggplot(., aes(x = Library, y = reads)) + 
    geom_boxplot(aes(fill = Library, alpha = 1), outlier.colour = "black") +
    geom_jitter(width = 0.05, color = "black") +
    facet_wrap(~step) +
    theme_classic() +
    scale_fill_manual(values = c(double_color, single_color)) +
    scale_shape_manual(values = c(16, 18)) +
    labs(x = "Library Type",
         y = expression(Reads ~ (x10^6)),
         color = "Strandedness") +
    expand_limits(y = 11) +
    guides(alpha = "none") +
    geom_text(data = annotations, aes(x = 1.5, y = y_position, label = annotation), vjust = -0.5) +
    expand_limits(y = c(0, 10)) +
    scale_y_continuous(breaks = c(0, 2, 4, 6, 8, 10), labels = c("0", "2", "4", "6", "8", "10")) 
    

eager_counts_plots

#ggsave("./06-publication/supplemental_figures/SI_Fig13A_npre_eager_read_counts_boxplot_color.pdf", plot = eager_counts_plots, device = "pdf", scale = 1, width = 9, height = 5, units = c("in"), dpi = 300)
```


#Median reduction in read length

```{r}
#function to find median read length throughout process 
median_rl_summary_table <- function(metadata, sample_list, adapter_removal_data, remove_less_30_data, samtools_data, cutadapt_data) {
  
  #Create a blank data frame with each column of interest
  read_length_summary_table <- data.frame(Sample = sample_list,
                                          adapter_ds = numeric(length(sample_list)),
                                          adapter_ss = numeric(length(sample_list)),
                                          remove_less_30_ds = numeric(length(sample_list)),
                                          remove_less_30_ss = numeric(length(sample_list)),
                                          artifact_removal_ds = numeric(length(sample_list)),
                                          artifact_removal_ss = numeric(length(sample_list)),
                                          cutadapt_ds = numeric(length(sample_list)),
                                          cutadapt_ss = numeric(length(sample_list)),
                                          stringsAsFactors = FALSE)
  
  #Function to calculate median read length based on dataset, sample, and strandedness
  calculate_median_rl <- function(data, sample, strandedness) {
    rl_summary <- metadata %>%
      full_join(., data, by = "Library_ID") %>%
      dplyr::select(Library_ID, Individual_ID, Strandedness, Length, counts) %>%
      mutate(Length = as.integer(as.character(Length))) %>%
      filter(Individual_ID == sample, Strandedness == strandedness) %>%
      uncount(counts) %>%
      mutate(Length = as.integer(Length)) %>%
      summarize(median_rl = median(Length)) 
    
      return(rl_summary$median_rl)
  }
  
  
  for (sample in sample_list) {
    #adapter removal
    rl_value_of_median_ds <- calculate_median_rl(adapter_removal_data, sample, "Double")
    rl_value_of_median_ss <- calculate_median_rl(adapter_removal_data, sample, "Single")
    read_length_summary_table[read_length_summary_table$Sample == sample, "adapter_ds"] <- rl_value_of_median_ds
    read_length_summary_table[read_length_summary_table$Sample == sample, "adapter_ss"] <- rl_value_of_median_ss
    
    #remove read less than 30bp
    rl_value_of_median_ds <- calculate_median_rl(remove_less_30_data, sample, "Double")
    rl_value_of_median_ss <- calculate_median_rl(remove_less_30_data, sample, "Single")
    read_length_summary_table[read_length_summary_table$Sample == sample, "remove_less_30_ds"] <- rl_value_of_median_ds
    read_length_summary_table[read_length_summary_table$Sample == sample, "remove_less_30_ss"] <- rl_value_of_median_ss
    
    #remove sequencing and library artifacts (samtools)
    rl_value_of_median_ds <- calculate_median_rl(samtools_data, sample, "Double")
    rl_value_of_median_ss <- calculate_median_rl(samtools_data, sample, "Single")
    read_length_summary_table[read_length_summary_table$Sample == sample, "artifact_removal_ds"] <- rl_value_of_median_ds
    read_length_summary_table[read_length_summary_table$Sample == sample, "artifact_removal_ss"] <- rl_value_of_median_ss
    
    #cutadapt
    rl_value_of_median_ds <- calculate_median_rl(cutadapt_data, sample, "Double")
    rl_value_of_median_ss <- calculate_median_rl(cutadapt_data, sample, "Single")
    read_length_summary_table[read_length_summary_table$Sample == sample, "cutadapt_ds"] <- rl_value_of_median_ds
    read_length_summary_table[read_length_summary_table$Sample == sample, "cutadapt_ss"] <- rl_value_of_median_ss
  }

  return(read_length_summary_table)
  
}

rl_levels <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150)
```



```{r}
#Read in the read length data for each processing step:
sample_list <- metadata %>%
  dplyr::select(Individual_ID) %>%
  unique() %>%
  pull()

full_data_table <- metadata %>%
  dplyr::select(Sequencing_ID, Library_ID, Individual_ID, Strandedness) %>%
  mutate(Library_ID = str_replace_all(Library_ID, "_10M", ""))

rl_bins_adapterremoval <- fread("./05-results/normalize_eager/dsvss_npre_read_length_adapter_removal.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  mutate(Length = as.factor(Length))

rl_bins_remove30bp <- fread("./05-results/normalize_eager/dsvss_npre_read_length_remove30bp.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  mutate(Length = as.factor(Length))

rl_bins_artifact_removal <- fread("./05-results/normalize_eager/dsvss_npre_read_length_artifact_removal.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  mutate(Length = as.factor(Length))

rl_bins_cutadapt <- fread("./05-results/normalize_eager/dsvss_npre_read_length_cutadapt.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  mutate(Length = as.factor(Length))
```


```{r}
#create read_length_summary_table
median_rl_summary_table <- median_rl_summary_table(full_data_table, sample_list, rl_bins_adapterremoval, rl_bins_remove30bp, rl_bins_artifact_removal, rl_bins_cutadapt) 

median_rl_summary_table_ss <- median_rl_summary_table %>%
  rename(Individual_ID = 1) %>%
  dplyr::select(Individual_ID, adapter_ss, remove_less_30_ss, artifact_removal_ss, cutadapt_ss) %>%
  mutate(Strandedness = "Single") %>%
  rename(adapter_removal_median = 2, remove_less_30_median = 3, artifact_removal_median = 4, cutadapt_median = 5)
  
median_rl_summary_table_ds <- median_rl_summary_table %>%
  rename(Individual_ID = 1) %>%
  dplyr::select(Individual_ID, adapter_ds, remove_less_30_ds, artifact_removal_ds, cutadapt_ds) %>%
  mutate(Strandedness = "Double") %>%
  rename(adapter_removal_median = 2, remove_less_30_median = 3, artifact_removal_median = 4, cutadapt_median = 5)

read_length_median <- median_rl_summary_table_ss %>%
  full_join(., median_rl_summary_table_ds)  %>%
  pivot_longer(adapter_removal_median:cutadapt_median, names_to = "step", values_to = "median_read_length") %>%
  mutate(step = (factor(step, levels = c("adapter_removal_median", "remove_less_30_median", "artifact_removal_median", "cutadapt_median")))) %>%
  mutate(step = str_replace_all(step, "adapter_removal_median", "Reads After Adapter Removal and Merging"),
         step = str_replace_all(step, "remove_less_30_median", "Reads After Removing Reads <30bp"),
         step = str_replace_all(step, "artifact_removal_median", "Reads After Removing Sequencing and Lab Artifacts"),
         step = str_replace_all(step, "cutadapt_median", "Reads After Cutadapt")) %>%
  mutate(Library_type = Strandedness) %>%
  mutate(Library_type = str_replace_all(Library_type, "Double", "dsLib"),
         Library_type = str_replace_all(Library_type, "Single", "ssLib"))
 
read_length_median$step <- factor(read_length_median$step, levels = c("Reads After Adapter Removal and Merging", "Reads After Removing Reads <30bp", "Reads After Removing Sequencing and Lab Artifacts", "Reads After Cutadapt")) 

```


```{r}
#Read length before and after plot - colored by percent oral
#% read length lost 
#all sequenced PE 75 

read_length_median_percent <- read_length_median %>%
  mutate(pre_trim_avg_rl = 75) %>%
  mutate(percent_read_length_lost = 100 - (median_read_length/pre_trim_avg_rl)*100)

kraken2_filtered_oral_species <- fread("./05-results/normalize_eager/dsvss_npre_no_rl_kraken2_gtdb207_oral_species_decontam_filtered.tsv") %>%
  adorn_totals() %>%
  filter(Species == "Total") %>%
  pivot_longer(!Species, names_to = "Sequencing_ID", values_to = "number_oral_reads") %>%
  mutate(number_oral_reads = as.numeric(number_oral_reads)) %>%
  dplyr::select(-Species)

number_species <- kraken2_filtered_oral_species %>%
  mutate(Sequencing_ID = str_replace_all(Sequencing_ID, "_10M", "")) %>%
  full_join(., metadata) %>%
  rename(Sample = Individual_ID, Library = Strandedness) %>%
  mutate(Library = str_replace(Library, "Double", "dsLib"),
         Library = str_replace(Library, "Single", "ssLib")) %>%
  mutate(percent_oral_reads = (number_oral_reads/Initial_reads)*100) 

read_length_median_percent <- read_length_median_percent %>%
  filter(str_detect(step, "Reads After Cutadapt")) %>%
  rename(Library = Library_type, Sample = Individual_ID) %>%
  full_join(., number_species) 

wilcox_results <- read_length_median_percent %>%
  wilcox_test(percent_read_length_lost ~ Strandedness, paired = TRUE) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance("p.adj")

effect_size_labels <- read_length_median_percent %>%
  wilcox_effsize(formula = percent_read_length_lost ~ Strandedness, paired = TRUE) %>%
  mutate(effectsize_cat = case_when(
    magnitude == "small" ~ "†",     
    magnitude == "moderate" ~ "††",
    magnitude == "large" ~ "†††"))

wilcox_results <- wilcox_results %>%
  left_join(effect_size_labels) %>%
  mutate(annotation = paste(p.adj.signif, effectsize_cat))

annotations <- wilcox_results %>%
  summarize(annotation = first(annotation),
            y_position = 54, .groups = 'drop')

read_length_median_percent_plot <- read_length_median_percent %>%
  ggplot(., aes(x = Library, y = percent_read_length_lost)) + 
  geom_boxplot() +
  geom_jitter(width = 0.075, size = 3, aes(color = percent_oral_reads)) +
  scale_color_viridis(option = "viridis", begin = 0.1) +
  theme_classic() +
  scale_shape_manual(values = c(16, 18)) +
  labs(x = "Library Type",
       y = "Percent Reduction in Read Length",
       color = "Percent of Reads Classified as Oral") +
  expand_limits(y = 60) +
  guides(alpha = FALSE) +
  geom_text(data = annotations, aes(x = 1.5, y = y_position, label = annotation), vjust = -0.5, size = 5) +
  theme(axis.text.x = element_text( size = 12), 
          axis.text.y = element_text(size = 12), 
          axis.title = element_text(size = 14),  
          legend.text = element_text(size = 12),  
          legend.title = element_text(size = 14),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
  geom_line(aes(group = Sample), linetype = "dashed", color = "#555555", linewidth = 0.2) +
  geom_text_repel(aes(label = Sample), size = 2)

read_length_median_percent_plot

#ggsave("./06-results/supplemental_figures/SI_Fig13B_npre_eager_percent_rl_lost_w_lines.pdf", plot = read_length_median_percent_plot, device = "pdf", scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)

```


#GC change (%) after processing
```{r}
#Function to calculate the meadian GC content of each library throughout process 
median_gc_summary_table <- function(metadata, sample_list, adapter_removal_data, remove_less_30_data, artifact_removal_data, cutadapt_data) {
  
  #Create a blank dataframe
  gc_summary_table <- data.frame(Sample = sample_list,
                                          adapter_ds = numeric(length(sample_list)),
                                          adapter_ss = numeric(length(sample_list)),
                                          remove_less_30_ds = numeric(length(sample_list)),
                                          remove_less_30_ss = numeric(length(sample_list)),
                                          artifact_removal_ds = numeric(length(sample_list)),
                                          artifact_removal_ss = numeric(length(sample_list)),
                                          cutadapt_ds = numeric(length(sample_list)),
                                          cutadapt_ss = numeric(length(sample_list)),
                                          stringsAsFactors = FALSE)
  
  #Function to calculate median read length based on dataset, sample, and strandedness
  calculate_median_gc <- function(data, sample, strandedness) {
    
    gc_summary <- metadata %>%
      full_join(., data, by = "Library_ID") %>%
      dplyr::select(Library_ID, Individual_ID, Strandedness, gc, counts) %>%
      filter(Individual_ID == sample, Strandedness == strandedness) %>%
      mutate(gc = as.integer(as.character(gc))) %>%
      uncount(counts) %>%
      summarize(median = median(gc))
    
    return(gc_summary$median)
  }
  
  
  for (sample in sample_list) {
    #adapter removal
    gc_value_of_median_ds <- calculate_median_gc(adapter_removal_data, sample, "Double")
    gc_value_of_median_ss <- calculate_median_gc(adapter_removal_data, sample, "Single")
    gc_summary_table[gc_summary_table$Sample == sample, "adapter_ds"] <- gc_value_of_median_ds
    gc_summary_table[gc_summary_table$Sample == sample, "adapter_ss"] <- gc_value_of_median_ss
    
    #remove read less than 30bp
    gc_value_of_median_ds <- calculate_median_gc(remove_less_30_data, sample, "Double")
    gc_value_of_median_ss <- calculate_median_gc(remove_less_30_data, sample, "Single")
    gc_summary_table[gc_summary_table$Sample == sample, "remove_less_30_ds"] <- gc_value_of_median_ds
    gc_summary_table[gc_summary_table$Sample == sample, "remove_less_30_ss"] <- gc_value_of_median_ss
    
    #remove sequencing and lab artifacts (samtools)
    gc_value_of_median_ds <- calculate_median_gc(artifact_removal_data, sample, "Double")
    gc_value_of_median_ss <- calculate_median_gc(artifact_removal_data, sample, "Single")
    gc_summary_table[gc_summary_table$Sample == sample, "artifact_removal_ds"] <- gc_value_of_median_ds
    gc_summary_table[gc_summary_table$Sample == sample, "artifact_removal_ss"] <- gc_value_of_median_ss
    
    #cutadapt
    gc_value_of_median_ds <- calculate_median_gc(cutadapt_data, sample, "Double")
    gc_value_of_median_ss <- calculate_median_gc(cutadapt_data, sample, "Single")
    gc_summary_table[gc_summary_table$Sample == sample, "cutadapt_ds"] <- gc_value_of_median_ds
    gc_summary_table[gc_summary_table$Sample == sample, "cutadapt_ss"] <- gc_value_of_median_ss
  }

  return(gc_summary_table)
  
}

gc_levels <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104)

```


```{r}
sample_list <- metadata %>%
  dplyr::select(Individual_ID) %>%
  unique() %>%
  pull()

full_data_table <- metadata %>%
  dplyr::select(Sequencing_ID, Library_ID, Individual_ID, Strandedness) %>%
  mutate(Library_ID = str_replace_all(Library_ID, "_10M", ""))

#read in the gc data for each step
gc_bins_adapterremoval <- fread("./05-results/normalize_eager/dsvss_npre_gc_adapter_removal.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  separate(gc_bin, into = c("drop", "gc"), sep = ",", remove = FALSE) %>%
  mutate(gc = str_remove(gc, "\\]")) %>%
  dplyr::select(-gc_bin, -drop) %>%
  mutate(gc = as.factor(gc))

gc_bins_remove30bp <- fread("./05-results/normalize_eager/dsvss_npre_gc_remove30bp.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  separate(gc_bin, into = c("drop", "gc"), sep = ",", remove = FALSE) %>%
  mutate(gc = str_remove(gc, "\\]")) %>%
  dplyr::select(-gc_bin, -drop) %>%
  mutate(gc = as.factor(gc))

gc_bins_artifact_removal <- fread("./05-results/normalize_eager/dsvss_npre_gc_artifact_removal.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  separate(gc_bin, into = c("drop", "gc"), sep = ",", remove = FALSE) %>%
  mutate(gc = str_remove(gc, "\\]")) %>%
  dplyr::select(-gc_bin, -drop) %>%
  mutate(gc = as.factor(gc))

gc_bins_cutadapt <- fread("./05-results/normalize_eager/dsvss_npre_gc_cutadapt.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  separate(gc_bin, into = c("drop", "gc"), sep = ",", remove = FALSE) %>%
  mutate(gc = str_remove(gc, "\\]")) %>%
  dplyr::select(-gc_bin, -drop) %>%
  mutate(gc = as.factor(gc))

#create gc_summary_table
median_gc_summary_table <- median_gc_summary_table(full_data_table, sample_list, gc_bins_adapterremoval, gc_bins_remove30bp, gc_bins_artifact_removal, gc_bins_cutadapt) 

median_gc_summary_table_ss <- median_gc_summary_table %>%
  rename(Individual_ID = 1) %>%
  dplyr::select(Individual_ID, adapter_ss, remove_less_30_ss, artifact_removal_ss, cutadapt_ss) %>%
  mutate(Strandedness = "Single") %>%
  rename(adapter_removal_median = 2, remove_less_30_median = 3, artifact_removal_median = 4, cutadapt_median = 5) 
  
median_gc_summary_table_ds <- median_gc_summary_table %>%
  rename(Individual_ID = 1) %>%
  dplyr::select(Individual_ID, adapter_ds, remove_less_30_ds, artifact_removal_ds, cutadapt_ds) %>%
  mutate(Strandedness = "Double") %>%
  rename(adapter_removal_median = 2, remove_less_30_median = 3, artifact_removal_median = 4, cutadapt_median = 5)

gc_median <- median_gc_summary_table_ss %>%
  full_join(., median_gc_summary_table_ds)  %>%
  pivot_longer(adapter_removal_median:cutadapt_median, names_to = "step", values_to = "median_gc") %>%
  mutate(step = (factor(step, levels = c("adapter_removal_median", "remove_less_30_median", "artifact_removal_median", "cutadapt_median")))) %>%
  mutate(step = str_replace_all(step, "adapter_removal_median", "Reads After Adapter Removal and Merging"),
         step = str_replace_all(step, "remove_less_30_median", "Reads After Removing Reads <30bp"),
         step = str_replace_all(step, "artifact_removal_median", "Reads After Removing Sequencing and Lab Artifacts"),
         step = str_replace_all(step, "cutadapt_median", "Reads After Cutadapt")) %>%
  mutate(Library_type = Strandedness) %>%
  mutate(Library_type = str_replace_all(Library_type, "Double", "dsLib"),
         Library_type = str_replace_all(Library_type, "Single", "ssLib"))
 
gc_median$step <- factor(gc_median$step, levels = c("Reads After Adapter Removal and Merging", "Reads After Removing Reads <30bp", "Reads After Removing Sequencing and Lab Artifacts", "Reads After Cutadapt")) 

```


```{r}
gc_content <- fread("./05-results/normalize_eager/dsvss_npre_gc_content_before_processing.tsv") %>%
  separate(Study, into = "Library_ID", sep = ".10M", extra = "drop") %>%
  separate(Library_ID, into = "Library_ID", sep = ".SG1", extra = "drop") %>%
  rename(counts = 2) %>%
  separate(gc_bin, into = c("drop", "gc"), sep = ",", remove = FALSE) %>%
  mutate(gc = str_remove(gc, "\\]")) %>%
  dplyr::select(-gc_bin, -drop) %>%
  mutate(gc = as.factor(gc))

median_gc_summary_table_raw_reads <- function(metadata, sample_list, raw_reads_data) {
  
  #Create a blank dataframe
  gc_summary_table <- data.frame(Sample = sample_list,
                                          raw_reads_ds = numeric(length(sample_list)),
                                          raw_reads_ss = numeric(length(sample_list)),
                                          stringsAsFactors = FALSE)
  
  #Function to calculate median read length based on dataset, sample, and strandedness
  calculate_median_gc <- function(data, sample, strandedness) {
    
    gc_summary <- metadata %>%
      full_join(., data, by = "Library_ID") %>%
      dplyr::select(Library_ID, Individual_ID, Strandedness, gc, counts) %>%
      filter(Individual_ID == sample, Strandedness == strandedness) %>%
      mutate(gc = as.integer(as.character(gc))) %>%
      uncount(counts) %>%
      summarize(median = median(gc))

    return(gc_summary$median)
  }
  
  
  for (sample in sample_list) {
    #raw reads before eager
    gc_value_of_median_ds <- calculate_median_gc(raw_reads_data, sample, "Double")
    gc_value_of_median_ss <- calculate_median_gc(raw_reads_data, sample, "Single")
    gc_summary_table[gc_summary_table$Sample == sample, "raw_reads_ds"] <- gc_value_of_median_ds
    gc_summary_table[gc_summary_table$Sample == sample, "raw_reads_ss"] <- gc_value_of_median_ss

  }

  return(gc_summary_table)
  
}

pre_eager_median_gc <- median_gc_summary_table_raw_reads(full_data_table, sample_list, gc_content)

pre_eager_median_gc_ss <- pre_eager_median_gc %>%
  rename(Individual_ID = 1) %>%
  dplyr::select(Individual_ID, raw_reads_ss) %>%
  mutate(Strandedness = "Single") %>%
  rename(raw_reads_median = 2)
  
pre_eager_median_gc_ds <- pre_eager_median_gc %>%
  rename(Individual_ID = 1) %>%
  dplyr::select(Individual_ID, raw_reads_ds) %>%
  mutate(Strandedness = "Double") %>%
  rename(raw_reads_median = 2)

gc_median_pre_eager <- pre_eager_median_gc_ss %>%
  full_join(., pre_eager_median_gc_ds)  %>%
  mutate(Library_type = Strandedness) %>%
  mutate(Library_type = str_replace_all(Library_type, "Double", "dsLib"),
         Library_type = str_replace_all(Library_type, "Single", "ssLib")) %>%
  mutate(step = "pre_eager") %>%
  rename(median_gc = raw_reads_median)
```


```{r}
gc_median_full <- gc_median %>%
  full_join(., gc_median_pre_eager) %>%
  filter(!str_detect(step, "Reads After Adapter Removal"),
         !str_detect(step, "Reads After Removing Reads <30bp"),
         !str_detect(step, "Reads After Removing Sequencing and Lab Artifacts")) %>%
  pivot_wider(names_from = "step", values_from = "median_gc") %>%
  rename(post_processing = 'Reads After Cutadapt') %>%
  mutate(percent_gc_change = ((post_processing - pre_eager)/pre_eager)*100 ) %>%
  rename(Library = Library_type, Sample = Individual_ID) %>%
  full_join(., number_species) 

wilcox_results <- gc_median_full %>%
  wilcox_test(percent_gc_change ~ Strandedness, paired = TRUE) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance("p.adj")

effect_size_labels <- gc_median_full %>%
  wilcox_effsize(formula = percent_gc_change ~ Strandedness, paired = TRUE) %>%
  mutate(effectsize_cat = case_when(
    magnitude == "small" ~ "†",     
    magnitude == "moderate" ~ "††",
    magnitude == "large" ~ "†††"))

wilcox_results <- wilcox_results %>%
  left_join(effect_size_labels) %>%
  mutate(annotation = paste(p.adj.signif, effectsize_cat))

annotations <- wilcox_results %>%
  summarize(annotation = first(annotation),
            y_position = 18, .groups = 'drop')

gc_change_plot <- gc_median_full %>%
  ggplot(., aes(x = Library, y = percent_gc_change)) + 
  geom_boxplot() +
  geom_jitter(width = 0.075, size = 3, aes(color = percent_oral_reads)) +
  scale_color_viridis(option = "viridis", begin = 0.1) +
  theme_classic() +
  scale_shape_manual(values = c(16, 18)) +
  labs(x = "Library Type",
       y = "Percent GC Change",
       color = "Percent of Reads Classified as Oral") +
  expand_limits(y = 20) +
  guides(alpha = FALSE) +
  geom_text(data = annotations, aes(x = 1.5, y = y_position, label = annotation), vjust = -0.5, size = 5) +
  theme(axis.text.x = element_text( size = 12), 
          axis.text.y = element_text(size = 12), 
          axis.title = element_text(size = 14),  
          legend.text = element_text(size = 12),  
          legend.title = element_text(size = 14),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
  geom_line(aes(group = Sample), linetype = "dashed", color = "#555555", linewidth = 0.2) +
  geom_text_repel(aes(label = Sample), size = 2)

gc_change_plot

#ggsave("./06-publication/supplemental_figures/SI_Fig13C_npre_percent_gc_change.pdf", plot = gc_change_plot, device = "pdf", scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)
```

